# Generated by Django 4.0.5 on 2022-06-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_weathermodel_citiesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citiesmodel',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
