# Generated by Django 4.0.5 on 2022-06-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_citiesmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citiesmodel',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
